# Generated by Django 3.2.25 on 2026-08-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='blogsApp.Category'),
        ),
    ]
